config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/about_us', to: 'home#about_us'
  get '/history', to: 'home#history'
  get '/contacts', to: 'home#contacts'

  post '/search', to: "products#search"

  resources :products, only: :index, path: :catalog, as: :catalog
  resources :products, only: :show

  resources :staff_members, only: :index, path: :staff, as: :staff
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_images, dependent: :destroy
  has_many :product_properties, dependent: :destroy
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
end

app/models/product_property.rb
class ProductProperty < ApplicationRecord
  belongs_to :product
end

app/models/staff_member.rb
class StaffMember < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about_us; end
  def contacts; end
  def index; end
  def history; end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product = Product.all
  end

  def search
    product = FuzzyMatch.new(Product.all, read: :name).find(params['name'])
    if product.present?
      redirect_to product_path(product.id)
    else
      redirect_to catalog_index_path, alert: "Вашего тура не найдено. Ознакомтесь с каталогом."
    end
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/staff_members_controller.rb
class StaffMembersController < ApplicationController
  def index
    @staff = StaffMember.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/staff_members_helper.rb
module StaffMembersHelper
end

app/views/home/catalog.html.erb
<H2 align="left">Каталог</H2>
<div class="container">
    <div class="row">
      <% @product.each do |prod| %>
        <div class="col-6">
          <%= image_tag prod.product_images.find_by(title: "Title").image, align:"left", class:"mb-3 w-50" %>
          <div>
              <%= prod.name %>
              <div class="mt-3">Цена поездки: <%= prod.price %> ₽</div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/home/contacts.html.erb
<H2 align="left">Напишите нам!</H2>
<form>
	<div class="form-group mb-3">
		<input type="name" class="form-control mb-3" id="exampleFormControlInput1" placeholder="Имя">
		<input type="email" class="form-control mb-3" id="exampleFormControlInput1" placeholder="Email">
		<input type="tema" class="form-control mb-3" id="exampleFormControlInput1" placeholder="Тема">
		<textarea type="dis" class="form-control mb-3" id="exampleFormControlInput1" placeholder="Описание"></textarea>
		<button type="button" class="btn btn-success">Отправить</button>
	</div>
	<h4>Контакты</h4>
	<p>Телефон: 8(495)223-92-76 (с 9 до 19 ч. пн-пт)</p>

	<p>Email: zakaz.goldenmiddle@mail.ru</p>

	<p>Адрес: 117042, г. Москва, Чечерский пр-зд д. 24 , пом. 1, комн. 2, оф. 56</p>
</form>

app/views/home/history.html.erb
<H2 align="left">История</H2>
<p>Туристическая компания "Золотая Середина" осуществляете туроператорскую деятельность c 2004 года. Мы являемся официальным туроператором по России и внесены в Единый федеральный реестр туроператоров под номером РТО 006197. Деятельность нашей фирмы одобрена Федеральным агентством по туризму РФ и застрахована в компании "Гелиос".</p>
<%= image_tag "img/gold.jpg", align:"justify", width:"100%", class:"mb-3" %>
<p>Мы делаем экскурсии из Москвы и 30 городов Подмосковья. Экскурсии проводят профессиональные экскурсоводы. Для программы отбираются только самые интересные достопримечательности. Вы можете выбрать размещение, тип питания, место посадки в автобусе. Сервис и уровень обслуживания на очень высоком уровне!</p>

<p>Современные автобусы вместимостью 49-57 мест полностью оборудованы для дальних туристических поездок (откидные сиденья, туалет, тв, микрофон, климат-контроль, большие багажники), что гарантирует Ваш комфорт и спокойствие в дороге. Все используемые автобусы имеют Лицензию на транспортные перевозки пассажиров, в том числе детей, и медицинскую страховку на каждого пассажира до 2 млн. руб. Перед каждой поездкой автобусы проходят тщательный техосмотр, а водители - медицинское освидетельствование о состоянии здоровья. На многодневные экскурсии обязательно отправляется два водителя. Отслеживание передвижения автобусов в режиме онлайн с помощью спутников по ГЛОНАССУ. Для небольших групп 18-20 человек используются микроавтобусы Mercedes Sprinter.</p>

<p>Каждый год мы создаем новые маршруты!<strong> Путешествуйте с нами!</strong></p>

app/views/home/index.html.erb
<H1  align="left">Сборные туры на Кавказ</H1>
<h2>Летим организованной группой из Москвы!</h2>
<%= image_tag "img/g.jpg",align:"justify", width:"100%" %>
<p>
  Вы зашли на сайт официального <span class="videl-red">туроператора по России «Золотая Середина»</span>. Здесь Вы можете записаться на автобусные экскурсии из Москвы и разных городов Подмосковья или заказать необходимый тур для своей группы на автобусе или поезде. Наш опыт организации экскурсий более 10 лет! Наличие проверенных экскурсоводов в Москве, Казани, Санкт-Петербурге, Пскове, Дивеево, Селигере и других исторических городах.
</p>
<p>
  Вы можете быть уверены, что мы подберем для Вас лучший вариант транспорта, экскурсионной программы тура, питания в кафе, размещения в комфортном отеле и развлекательной программы для наших клиентов. По Вашей просьбе, мы заменим обед в программе на постный или вегетарианский, а влюбленных пар, во время многодневных экскурсий автобусом, разместим в номерах с 2-спальной кроватью.
</p>
<p>
  На экскурсиях сборных групп возможна оплата наличными при посадке в транспорт или по безналу для организаций. Группам от 5 человек – стоимость ж/д или автобусного тура по детскому билету, а от 10 человек – 1 билет бесплатно. Для постоянных клиентов бесплатное смс-оповещение о новых<strong> экскурсиях по России от GoldenMiddle.</strong>
</p>
<p>
  Заранее известны посадочные места, согласованные с каждым туристом. Вы можете быть спокойны, что приедет современный транспорт с кондиционером и удобными сиденьями.
</p>
<p>
  С нашей <span class="videl-blue">туристической фирмой Golden Middle</span> Вы сможете:
  - заказать школьный тур на автобусе или поезде по Москве и России;
  - организовать корпоративный выезд для сотрудников вашей компании;
  - путешествовать в составе наших сборных групп на автобусе, поезде, самолете по Москве, Подмосковью, Золотому Кольцу и всей России.
  - подобрать круиз по рекам России;
  - заказать прием Вашей группы в городах России.
</p>
<p><i>
  Ежегодно подтверждаем статус туроператора в Едином федеральном реестре Ростуризма под номером ВНТ 006197.
</i>	</p>
<p>
  Сотрудничество с «Золотой Серединой» – это гарантия качества и лучшей цены Вашего путешествия! Мы действительно находим золотую середину (оптимальный вариант) во всем, что делаем для Вас! Отдыхайте только вместе с нами!
</p>

app/views/home/staff.html.erb
<H2 align="left">Сотрудники</H2>
<div class="container">
  <div class="row">
    <% @staff.each do |staff_member| %>
      <div class="col-6">
        <%= image_tag staff_member.image, align: "left", class: "mb-3" %>
        <div class="fl_cl">
          <h4><%= staff_member.name %></h4>
          <h5><%= staff_member.profession %></h5>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<html lang="ru">
<head>
  <title>Туроператор "Золотая Середина"</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body class="back">
<div class="cont">
<table border="0" width="1200" cellpadding="0" cellspacing="0" align="center" bgcolor="#CACACA">
  <tr>
    <td width="150" align="center"><%= image_tag "img/logo.png", class: "mb-2" %></td>
    <td align="center"><H1>Золотая Середина</H1></td>
    <td width="270">
      <table  cellpadding="5"  width="100%">
        <%= form_with url: search_path do |form| %>
          <%= form.text_field :name, class: "my-2 form-control w-95", placeholder: "Введите название тура" %>
          <%= form.submit "Найти тур", class: "btn btn-light w-95" %>
        <% end %>
      </table>
    </td>
  </tr>
</table>

<table border="0" width="1200" cellpadding="5" cellpadding="0" align="center" bgcolor="#ECECEC">
  <tr>
    <td align="center"><%= link_to 'Главная', root_path %></td>
    <td align="center"><%= link_to 'Каталог', catalog_index_path %></td>
    <td align="center"><%= link_to 'Контакты', contacts_path %></td>
  </tr>
</table>
<BR>
<table border="0" width="1200" cellpadding="5" cellpadding="0" align="center">
  <tr>
    <td class="ht" width="150" valign="top" align="center" bgcolor="#ECECEC">
      <div class="mb-4 mt-2"><%= link_to 'О нас', about_us_path %><BR></div>
      <div class="mb-4"><%= link_to 'История фирмы', history_path %><BR></div>
      <div class="mb-4"><%= link_to 'Сотрудники', staff_index_path %><BR></div>
      <div class="ht back"></div>
    </td>
    <td>
      <%= yield %>
    </td>
</table>
</div>
<hr/>
<p align="center">
  © <%= Time.now.year %> — Все права защищены
</p>
</body>
</html>

app/views/products/index.html.erb
<h5 class="mb-2 videl-red-no-underline"><%= flash[:alert] if flash[:alert] %></h5>
<h2 align="left">Каталог</h2>
<div class="container">
    <div class="row">
      <% @product.each do |product| %>
        <div class="col-6">
          <%= image_tag product.product_images.find_by(title: "Title").image, align:"left", class:"mb-3 w-50" %>
          <div>
              <%= link_to product.name, product_path(product.id) %>
              <div class="mt-3">Цена поездки: <%= product.price.round %> ₽</div>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/products/show.html.erb
<%= link_to "Назад к каталогу", catalog_index_path, class: 'btn btn-secondary' %>
<h1><%= @product.name %></h1>
<h2>Описание услуги</h2>
<%= image_tag @product.product_images.find_by(title: 'Title').image, width: "50%", align: "justify" %>
<p><%= @product.short_description %></p>
<% # html_safe_translation(@product.description) %>
<table border="3" cellpadding="20" cellspacing="5">
	<tr>
		<td colspan=4 align="center">Стоимость тура</td>

	</tr>
	<tr>
		<td colspan=2 align="center">Дагестан</td>
		<td colspan=2 align="center">Чечня</td>
	</tr>
	<tr>
		<td>Детский билет</td>
		<td>Взрослый билет</td>
		<td>Детский билет</td>
		<td>Взрослый билет</td>
	</tr>
	<tr>
		<td>20000</td>
		<td>27000</td>
		<td>15000</td>
		<td>19000</td>
	</tr>
</table><BR>
<h5>Описание тура</h5>
<ol type="circle">
	<li> День 1
		<ol type="a">
			<li><span class="videl-red">Вылет из Москвы</span> в 10.00 утра. Есть рейс из Шереметьево и Внуково. Перелет до города Минеральные Воды. Помогаем приобрести билеты.</li>
			<li><span class="videl-red">Прибытие в 12.30 в Минеральные Воды</span>Встреча на джипах прямо из аэропорта. В пути на Плато Бермамыт вы увидите горные пейзажи и диких лошадей</li>
			<li><span class="videl-red">Джиптур на Плато Бермамыт</span> это часть Скалистого хребта Большого Кавказа. Его название переводится как «кривое колено». Рельеф места действительно необычный: причудливые колонны, асимметричные склоны и ущелья выглядят, словно декорации в кино. Вершина плато, Большой Бермамыт, находится на высоте 2592 метра над уровнем моря. Сюда едут, чтобы полюбоваться видом на Эльбрус и невероятные закаты, который мы и увидим, а также сделаем прекрасные фото.</li>
			<li><span class="videl-red">Можно пообедать в горном кафе</span> в 10.00 утра. Есть рейс из Шереметьево и Внуково. Перелет до города Минеральные Воды. Помогаем приобрести билеты.</li>
			</li>
		</ol>
	</li>
</ol>
<li> День 2
	<ol type="a">
		<li><span class="videl-red">Завтрак в отеле "шведский стол"</span>
		</li>
		<li><span class="videl-red">Экскурсия на Чегемские водопады</span> это визитная карточка Кабардино-Балкарии. Здесь сплетаются между собой две стихии вода и камень, образуя невероятные и, порой, фантастические пейзажи. Чегемское ущелье - входит в список самых красивых мест Кабардино-Балкарской Республики. Оно представляет собой огромный 15-метровый разлом в горе, высотой около 300 метров. Стены разлома на этом участке максимально сужаются и путнику кажется, что горы закрывают небо. По его дну течет горная река Чегем. Существует легенда, что каньон образовался от удара лошадиного копыта, когда богатырь Карашауая скакал по горам Кавказа.
		</li>
		<li><span class="videl-red">Водопад Абай-Су</span> это самый высокий некаскадный 78-ми метровый водопад  Кабардино-Балкарии, спадающий с базальтовых скал. Свое название водопад получил от имени одного из охотников — Абая, известного своей меткостью.
		</li>
	</ol>
</li>

app/views/staff_members/index.html.erb
<H2 align="left">Сотрудники</H2>
<div class="container">
  <div class="row">
    <% @staff.each do |staff_member| %>
      <div class="col-6">
        <%= image_tag staff_member.image, align: "left", class: "mb-3" %>
        <div class="fl_cl">
          <h4><%= staff_member.name %></h4>
          <h5><%= staff_member.profession %></h5>
        </div>
      </div>
    <% end %>
  </div>
</div>